st = input('Digit some thing: ')
print('Is "alnum": ', st.isalnum())
print('Is "alpha": ', st.isalpha())
print('Is "lower": ', st.islower())
print('Is "numeric": ', st.isnumeric())
print('Is "upper": ', st.isupper())
print('Is "printable": ', st.isprintable())
